"""
URL configuration for backend project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from rest_framework.routers import DefaultRouter
from parking.views import ParkingLocationViewSet, ParkingSlotViewSet, ReservationViewSet
from accounts.views import UserViewSet, CustomTokenObtainPairView

# Registering viewsets with the router
# This allows us to automatically generate the URL patterns for these viewsets.
# The basename is used to create the URL names for the viewsets.
# It is important to ensure that the basename is unique across all registered viewsets.
router = DefaultRouter()
router.register(r'locations', ParkingLocationViewSet, basename='parkinglocation')
router.register(r'slots', ParkingSlotViewSet, basename='parkingslot')
router.register(r'reservations', ReservationViewSet, basename='reservation')
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    # Admin and API authentication URLs
    path('admin/', admin.site.urls),

    # API authentication URLs for JWT token management
    # These URLs handle token creation, refresh, and verification.
    # They are essential for securing API endpoints and managing user sessions.
    path('api-auth/', include('rest_framework.urls')),
    path('api/token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    # API URLs for the registered viewsets
    # These URLs are automatically generated by the router based on the registered viewsets.
    # They provide endpoints for CRUD operations on parking locations, slots, reservations, and users.
    path('api/', include(router.urls)),
    path('api/login/', CustomTokenObtainPairView.as_view(), name="token_obtain_pair")
]
